/**
 * generate-secrets script tests.
 *
 * SECURITY_AUDIT LOW-02: the script must refuse to print a private key without
 * an explicit confirm flag (--confirm-print-secrets or
 * --i-understand-this-prints-secrets). Without the flag it prints instructions
 * only and exits 0.
 */

import { describe, expect, test } from 'bun:test';
import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';

const SCRIPT = resolve(
  import.meta.dir,
  '../../scripts/generate-secrets.ts'
);

// Private keys generated by ethers are 32-byte hex, i.e. '0x' + 64 hex chars.
const PK_SHAPE = /0x[0-9a-fA-F]{64}/;

describe('generate-secrets confirm flag gate', () => {
  test('without the flag: prints instructions and never emits a private-key-shaped hex', () => {
    const out = spawnSync('bun', ['run', SCRIPT], {
      encoding: 'utf8',
      // Inherit env so bun can resolve node_modules; no confirm flag in argv.
      env: process.env,
    });
    expect(out.status).toBe(0);
    const combined = (out.stdout ?? '') + (out.stderr ?? '');
    // Must NOT print a 32-byte private key.
    expect(PK_SHAPE.test(combined)).toBe(false);
    // Should include the instructions verbatim so operators know how to opt in.
    expect(combined).toContain('--confirm-print-secrets');
  });

  test('with --confirm-print-secrets: prints a private-key-shaped hex', () => {
    const out = spawnSync(
      'bun',
      ['run', SCRIPT, '--confirm-print-secrets'],
      { encoding: 'utf8', env: process.env }
    );
    expect(out.status).toBe(0);
    const combined = (out.stdout ?? '') + (out.stderr ?? '');
    expect(PK_SHAPE.test(combined)).toBe(true);
  });
});
